#!/bin/ash

if [ "$1" == "" ] || [ "$2" == "" ]; then
  echo "Missing arguments BRANCH VCS_REF"
  exit 1
fi

rm -fr /phpipam

# Download software
git clone -b $1 --recursive --depth 1 https://github.com/phpipam/phpipam.git /phpipam

# Configure for Docker
echo -e "\n\ndefine('GIT_VCS_REF', '$2');" >>/phpipam/functions/version.php
ln -s /phpipam/config.docker.php /phpipam/config.php

# remove .git files
find /phpipam -name ".git*"        -exec rm -fr {} \;

# Set permissions
find /phpipam -type f              -exec chmod u=rw,go=r {} \;
find /phpipam -type d              -exec chmod u=rwx,go=rx {} \;
find /phpipam -type d -name upload -exec chmod a=rwx {} \;
chmod a=rwX /phpipam/css/images/logo
